/*
 * Artifact.java
 *
 * 31.03.2018
 *
 * (c) by O.Lieshoff
 *
 */

package archimedes.legacy.cf;

import static corentx.util.Checks.*;

/**
 * An rtifact generated by a code factory. 
 *
 * @author O. Lieshoff
 *
 * @changed OLI 31.03.2018 - Added.
 */

public class Artifact {

    private String code = null;
    private String sourceFileName = null;

    /**
     * Creates a new artifact with the passed parameters.
     *
     * @param code The code of the artifact.
     * @param sourceFileName The name of the source file which the artifact is linked to.
     * @throws IllegalArgumentException Passing a null pointer or an empty string as source
     *         file name.
     */
    public Artifact(String code, String sourceFileName) {
        super();
        ensure(code != null, "code cannot be null.");
        ensure(sourceFileName != null, "source file cannot be null.");
        ensure(!sourceFileName.isEmpty(), "source file cannot be empty.");
        this.code = code;
        this.sourceFileName = sourceFileName;
    }

    /**
     * Returns the content (mostly the source code) if the artifact.
     *
     * @return The content (mostly the source code) if the artifact.
     */
    public String getContent() {
        return this.code;
    }

    /**
     * Returns the name of the source file which the artifact is linked to.
     *
     * @return The name of the source file which the artifact is linked to.
     */
    public String getSourceFileName() {
        return this.sourceFileName;
    }

}